//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrizzioGsheetIntegration.Web.Models.CMmodels
{
    using System;
    using System.Collections.Generic;
    
    public partial class cmContactStep
    {
        public int Id { get; set; }
        public System.Guid ContactId { get; set; }
        public int ContactManagerId { get; set; }
        public System.Guid StepId { get; set; }
        public System.DateTime DateEntered { get; set; }
        public Nullable<System.DateTime> DateLeft { get; set; }
        public string ExtraInfo { get; set; }
        public Nullable<System.DateTime> DateArchived { get; set; }
        public System.Guid OwnerContactId { get; set; }
        public Nullable<System.DateTime> SnoozeUntil { get; set; }
    }
}
