//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrizzioGsheetIntegration.Web.Models.CMmodels
{
    using System;
    using System.Collections.Generic;
    
    public partial class cmContactOrder
    {
        public int Id { get; set; }
        public System.Guid ContactID { get; set; }
        public string ProductIds { get; set; }
        public decimal Amount { get; set; }
        public string Description { get; set; }
        public int OrderStatusId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public int TenantId { get; set; }
        public string AffiliateUpline { get; set; }
        public bool Confirmed { get; set; }
        public string PaymentType { get; set; }
        public Nullable<int> ContactManagerId { get; set; }
        public Nullable<System.Guid> Setter { get; set; }
        public Nullable<System.Guid> Closer { get; set; }
        public Nullable<System.Guid> Coach { get; set; }
    }
}
