//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrizzioGsheetIntegration.Web.Models.CMmodels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CMContext : DbContext
    {
        public CMContext()
            : base("name=CMContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cmContactStep> cmContactSteps { get; set; }
        public virtual DbSet<cmEntityData> cmEntityDatas { get; set; }
        public virtual DbSet<cmDialSessionCall> cmDialSessionCalls { get; set; }
        public virtual DbSet<cmContactOrder> cmContactOrders { get; set; }
        public virtual DbSet<FulfillmentOrder> FulfillmentOrders { get; set; }
    }
}
