//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrizzioGsheetIntegration.Web.Models.CMmodels
{
    using System;
    using System.Collections.Generic;
    
    public partial class cmDialSessionCall
    {
        public int Id { get; set; }
        public int DialSessionID { get; set; }
        public System.Guid ContactID { get; set; }
        public int SessionOrder { get; set; }
        public Nullable<bool> LiveAnswer { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public bool Completed { get; set; }
        public string Outcome { get; set; }
        public string OutcomeDetails { get; set; }
        public Nullable<int> ScriptRead { get; set; }
        public string CallGroup { get; set; }
    }
}
