//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrizzioGsheetIntegration.Web.Models.CMmodels
{
    using System;
    using System.Collections.Generic;
    
    public partial class cmEntityData
    {
        public int Id { get; set; }
        public System.Guid EntityID { get; set; }
        public string Data { get; set; }
        public System.Guid DefinitionId { get; set; }
        public System.Guid ContactID { get; set; }
    }
}
