//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrizzioGsheetIntegration.Web.Models.CMmodels
{
    using System;
    using System.Collections.Generic;
    
    public partial class FulfillmentOrder
    {
        public System.Guid FulfillmentOrderID { get; set; }
        public string PublicID { get; set; }
        public Nullable<System.Guid> CartOwnerContactUserID { get; set; }
        public Nullable<System.Guid> PurchaserContactID { get; set; }
        public Nullable<System.Guid> ShiptoContactID { get; set; }
        public string ShiptoFirstName { get; set; }
        public string ShiptoLastName { get; set; }
        public string ShiptoAddress1 { get; set; }
        public string ShiptoAddress2 { get; set; }
        public string ShiptoCity { get; set; }
        public Nullable<System.Guid> ShiptoStatePossessionID { get; set; }
        public string ShiptoPostalCode { get; set; }
        public Nullable<System.Guid> ShiptoCountryID { get; set; }
        public string ShiptoEmail { get; set; }
        public string ShiptoPhone { get; set; }
        public string BilltoFirstName { get; set; }
        public string BilltoLastName { get; set; }
        public string BilltoAddress1 { get; set; }
        public string BilltoAddress2 { get; set; }
        public string BilltoCity { get; set; }
        public Nullable<System.Guid> BilltoStatePossessionID { get; set; }
        public string BilltoPostalCode { get; set; }
        public Nullable<System.Guid> BilltoCountryID { get; set; }
        public string BilltoEmail { get; set; }
        public string BilltoPhone { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string OrderStatus { get; set; }
        public string OrderSource { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public Nullable<decimal> OrderSubtotal { get; set; }
        public Nullable<decimal> OrderSandHTotal { get; set; }
        public Nullable<decimal> OrderTaxTotal { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsArchive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.Guid CreatedByContactUserID { get; set; }
        public System.DateTime DateModified { get; set; }
        public System.Guid ModifiedByContactUserID { get; set; }
        public Nullable<long> ImportOriginID { get; set; }
        public string OriginTable { get; set; }
        public string Notes { get; set; }
        public int OrderID { get; set; }
        public int Phase { get; set; }
        public int DeclineCount { get; set; }
        public Nullable<System.Guid> CommisionEarnedByContactID { get; set; }
        public Nullable<int> ContactOrder_Id { get; set; }
    
        public virtual FulfillmentOrder FulfillmentOrder1 { get; set; }
        public virtual FulfillmentOrder FulfillmentOrder2 { get; set; }
    }
}
